export const budgetConstants = {
  GET_BUDGET_REQUEST_FAILURE: "GET_BUDGET_REQUEST_FAILURE",
  GET_BUDGET_REQUEST: "GET_BUDGET_REQUEST",
  GET_BUDGET: "GET_BUDGET",

  DELETE_EXPENSE: "DELETE_EXPENSE",
  DELETE_INCOME: "DELETE_INCOME",
  SET_SAVINGS: "SET_SAVINGS",
  ADD_EXPENSE: "ADD_EXPENSE",
  ADD_INCOME: "ADD_INCOME",
};
