export const budgetConstants = {
  BUDGET_REQUEST_FAILURE: "BUDGET_REQUEST_FAILURE",
  MAKE_BUDGET_REQUEST: "MAKE_BUDGET_REQUEST",
  GET_TOTAL_SPENT_BY_DAY: "GET_TOTAL_SPENT_BY_DAY",
  GET_TOTAL_SPENT: "GET_TOTAL_SPENT",
};
