export const receiptConstants = {
  UPLOAD_RECEIPT_PHOTO_FAILURE: "UPLOAD_RECEIPT_PHOTO_FAILURE",
  UPLOAD_RECEIPT_PHOTO_SUCCESS: "UPLOAD_RECEIPT_PHOTO_SUCCESS",
  UPLOAD_RECEIPT_PHOTO: "UPLOAD_RECEIPT_PHOTO",
  GET_RECEIPT_REQUEST_FAILURE: "GET_RECEIPT_REQUEST_FAILURE",
  GET_RECEIPT_REQUEST: "GET_RECEIPT_REQUEST",
  GET_RECEIPT_BY_ID: "GET_RECEIPT_BY_ID",
  GET_ALL_RECEIPTS: "GET_ALL_RECEIPTS",
  ADD_NEW_RECEIPT: "ADD_NEW_RECEIPT",
  DELETE_RECEIPT: "DELETE_RECEIPT",
};
