export const receiptConstants = {
  GET_RECEIPT_REQUEST: "GET_RECEIPT_REQUEST",
  GET_RECEIPT_BY_ID: "GET_RECEIPT_BY_ID",
  GET_ALL_RECEIPTS: "GET_ALL_RECEIPTS",
  ADD_NEW_RECEIPT: "ADD_NEW_RECEIPT",
  DELETE_RECEIPT: "DELETE_RECEIPT",
  GET_ALL_SELLERS: "GET_ALL_SELLERS",
  ADD_NEW_SELLER: "ADD_NEW_SELLER",
  UPDATE_SELLER: "UPDATE_SELLER",
};
