export const sellerConstants = {
  GET_SELLER_REQUEST_FAILURE: "GET_SELLER_REQUEST_FAILURE",
  GET_SELLER_REQUEST: "GET_SELLER_REQUEST",
  GET_SELLER_BY_ID: "GET_SELLER_BY_ID",
  GET_ALL_SELLERS: "GET_ALL_SELLERS",
  ADD_NEW_SELLER: "ADD_NEW_SELLER",
  UPDATE_SELLER: "UPDATE_SELLER",
};
