export const spendingConstants = {
  SPENDING_REQUEST_FAILURE: "SPENDING_REQUEST_FAILURE",
  MAKE_SPENDING_REQUEST: "MAKE_SPENDING_REQUEST",
  GET_TOTAL_SPENT_BY_DAYS: "GET_TOTAL_SPENT_BY_DAYS",
  GET_TOTAL_SPENT_BY_DAY: "GET_TOTAL_SPENT_BY_DAY",
  GET_TOTAL_SPENT: "GET_TOTAL_SPENT",
  GET_MONTHS_SPENT: "GET_MONTHS_SPENT",
  GET_RANGE_SPENT: "GET_RANGE_SPENT",
  GET_YEAR_SPENT: "GET_YEAR_SPENT",
};
